version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "build.gradle" }}
      - run:
          name: install aws cli
          command: |
            echo "${HOME}"
            sudo pip install awscli
      - run:
          name: download gpghome
          command: |
            aws s3 cp s3://gpghome-csun/gpghome.zip gpghome.zip
            unzip -a gpghome.zip
            echo "gpghome contents:"
            ls gpghome


      - run:
         name: install maven
         command: |
          sudo apt-get install maven
      - run:
          name: publish to maven
          command: |
            bash CircleciScripts/maven-release.sh

 
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples

 